### ISSUE TITLE
MVP: Construction Ship UI/ Can Construct

### ISSUE THREAD

**Issue by Steelstone3** [Steelstone3/Superior-Space-Domination#27]
Depends on #34 

- [x] Constructor ship UI taken from the basic UI (#15)
  - [x] Can construct new ships
  - [x] Can construct new facilities
  - [x] Cannot construct when not selected (Depends on #28)
- [x] Basic UI (Depends on #25)
  - [x] Change to a commander that determines the UI
